# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_type', models.CharField(choices=[('Offloading', 'Offloading'), ('Onloading', 'Onloading'), ('Techstop', 'Techstop')], default='', max_length=50, verbose_name='Handling Type')),
                ('task_date', models.DateField(verbose_name='Date')),
                ('flight_sta', models.TimeField(blank=True, default='', null=True)),
                ('task_info', models.CharField(default='', max_length=50, verbose_name='Plan Info')),
                ('task_status', models.CharField(choices=[('Standby', 'Standby'), ('Canceled', 'Canceled'), ('In_progress', 'In_progress'), ('New', 'New')], default='New', max_length=15)),
                ('task_approved', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_addtime', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('task_updatetime', models.DateTimeField(auto_now_add=True, verbose_name='Update')),
                ('flight_route_iata_from', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('route_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
                ('task_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
