# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(default='', max_length=50, verbose_name='Airline name')),
                ('description_rus', models.CharField(default='', max_length=255)),
                ('iata_code', models.CharField(default='', max_length=2)),
                ('icao_code', models.CharField(default='', max_length=3)),
                ('rus_code', models.CharField(default='', max_length=2)),
                ('country', models.CharField(default='', max_length=155)),
                ('alliance', models.CharField(default='', max_length=155)),
            ],
        ),
    ]
