# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('icao_code', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('rus_code', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('comment_eng', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('comment_rus', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('city_rus', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('s_utc', models.IntegerField(blank=True, default='', null=True)),
                ('w_utc', models.IntegerField(blank=True, default='', null=True)),
                ('airport_eng', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('airport_rus', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('comment_chn', models.CharField(blank=True, default='', max_length=155, null=True)),
                ('city_eng', models.CharField(blank=True, default='', max_length=155, null=True)),
            ],
        ),
    ]
