# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flight_date', models.DateField(default='', verbose_name='Flight Date')),
                ('flight_kind', models.CharField(choices=[('ARR', 'ARR'), ('DEP', 'DEP')], default='', max_length=10)),
                ('flight_number', models.CharField(default='', max_length=4, verbose_name='Flight Number')),
                ('flight_ac_reg_number', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Aircraft Registration')),
                ('flight_ac_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
                ('flight_co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
