# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('icao_code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('rus_code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('description_eng', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description_rus', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('wingspan', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('length', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('helicopter', models.CharField(blank=True, default='', max_length=1, null=True)),
                ('public_name_rus', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
